# cspell:ignore cirruslabs, deadlinks, difftastic, fblog, procs, lsusb, nmap, rustup, messense, appdir, openscad
homebrew_upgrade_all_packages: true

cargo_installed_binaries:
  - alacritty
  - atuin
  - bat
  - cargo-audit
  - cargo-auditable
  - cargo-binutils
  - cargo-bloat
  - cargo-clone
  - cargo-deadlinks
  - cargo-deb
  - cargo-deny
  - cargo-diet
  - cargo-edit
  - cargo-expand
  - cargo-generate
  - cargo-next
  - cargo-rpm
  - cargo-show-asm
  - cargo-tarpaulin
  - cargo-update
  - difftastic
  - dioxus-cli
  - du-dust
  - elf2uf2-rs
  - eza
  - fblog
  - fd-find
  - just
  - mdbook
  - procs
  - ripgrep
  - twiggy
  - watchexec-cli

homebrew_installed_packages:
  - asciinema
  - gh
  - git
  - htop
  - lsusb
  - neovim
  - nmap
  - open-ocd
  - openssl
  - rustup
  - tmux
  - xz

homebrew_taps:
  - { name: cirruslabs/cli, url: 'https://github.com/cirruslabs/homebrew-cli' }

homebrew_cask_appdir: /Applications

homebrew_cask_apps:
  - 1password
  - 1password-cli
  - autodesk-fusion
  - blender
  - brave-browser
  - cirruslabs/cli/tart
  - discord
  - docker
  - firefox@developer-edition
  - font-jetbrains-mono-nerd-font
  - kicad
  - omnigraffle
  - openscad
  - orcaslicer
  - postman
  - protonvpn
  - slack
  - visual-studio-code
  - zoom
