# cspell:ignore cirruslabs, deadlinks, difftastic, fblog, procs, lsusb, nmap, rustup, messense, appdir, openscad, duti, subfinder, ffuf, iterm, picotool

cargo_installed_binaries:
  - alacritty
  - atuin
  - { name: bacon, features: "clipboard sound" }
  - bat
  - cargo-audit
  - cargo-auditable
  - cargo-binutils
  - cargo-bloat
  - cargo-clone
  - cargo-deadlinks
  - cargo-deb
  - cargo-deny
  - cargo-diet
  - cargo-edit
  - cargo-expand
  - cargo-generate
  - cargo-next
  - cargo-nextest
  - cargo-rpm
  - cargo-show-asm
  - cargo-tarpaulin
  - cargo-update
  - difftastic
  - dioxus-cli
  - du-dust
  - elf2uf2-rs
  - eza
  - fblog
  - fd-find
  - just
  - mdbook
  - nu
  - probe-rs-tools
  - procs
  - ripgrep
  - starship
  - twiggy
  - { name: watchexec-cli, locked: true }

homebrew_upgrade_all_packages: true

homebrew_installed_packages:
  - ansible-lint
  - asciinema
  - cirruslabs/cli/tart
  - clamav
  - duti
  - ffuf
  - gcc
  - gh
  - git
  - htop
  - lld
  - llvm
  - lsusb
  - neovim
  - nmap
  - open-ocd
  - openssl
  - picotool
  - rustup
  - subfinder
  - tmux
  - xz
  - yamllint

homebrew_taps:
  - { name: cirruslabs/cli, url: 'https://github.com/cirruslabs/homebrew-cli' }

homebrew_cask_appdir: /Applications

homebrew_cask_apps:
  - 1password
  - 1password-cli
  - autodesk-fusion
  - blender
  - brave-browser
  - discord
  - docker
  - firefox@developer-edition
  - font-jetbrains-mono-nerd-font
  - gimp
  - iterm2
  - itermai
  - kicad
  - little-snitch
  - omnigraffle
  - openscad
  - orcaslicer
  - postman
  - protonvpn
  - slack
  - visual-studio-code
  - wireshark
  - zoom
